comment: false
language: R
sudo: false
cache: packages
after_success:
- Rscript -e 'covr::codecov()'
coverage:
  precision: 2
  round: down
  
  status:
      project:
        default:
          target: 90%