language: r
dist: trusty
cache: packages
addons:
  apt:
    packages:
    - tcl8.5-dev
    - tk8.5-dev

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

coverage:
  target: 90%

r_packages:
  - covr
  - drat

after_success:
  - travis_wait Rscript -e 'library(covr);codecov()'
  - test $TRAVIS_REPO_SLUG == "ELToulemonde/dataPreparation" && test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
